Feature: add tome uploader
spellshift/realm pull request #588
Opened 2024-02-14 01:16 UTC by alexcote1

#### What type of PR is this?

#### What this PR does / why we need it:
adds CLI app to upload tomes

2024-02-14 02:20 UTC, hulto commented
Fixes #465

2024-02-16 00:01 UTC, hulto commented on tavern/cli/tomeuploader/tomes/cat33/main.eldritch
Can you delete the "cats"

2024-02-16 15:38 UTC, KCarretto requested changes

2024-02-16 15:38 UTC, KCarretto commented on tavern/cli/tomeuploader/main.go
> +type Metadata struct {
Just import these types from "realm.pub/tavern/tomes"

2024-02-16 15:38 UTC, KCarretto commented on tavern/cli/tomeuploader/main.go
> +	cookie := os.Getenv("cookie")
nit: "AUTH_COOKIE"

2024-02-16 15:38 UTC, KCarretto commented on tavern/cli/tomeuploader/main.go
> +		// // Create the tome using GraphQL
nit: commented code

2024-02-16 15:38 UTC, KCarretto commented on tavern/cli/tomeuploader/main.go
> +	req.Header.Set("Content-Type", "application/json")
Just use token.Authenticate instead, have users pass in the token via env, and if none is set and a new token is obtained just save it to a file for now (and try reading the value if no env is set)

2024-02-16 15:38 UTC, KCarretto commented on tavern/cli/tomeuploader/main.go
> +	// Create files first and collect their IDs
nit: Commented code

2024-02-16 15:38 UTC, KCarretto commented on tavern/cli/tomeuploader/main.go
> +func processTomeDirectory(fs []fs.DirEntry, dirName string) (Metadata, string, []File, error) {
We can likely reuse some functionality from the "realm.pub/tavern/tomes" package here

2024-02-16 15:38 UTC, KCarretto commented on tavern/cli/tomeuploader/main.go
> +	fmt.Println(createTomeMutation)
nit: Remove println

2024-02-16 15:38 UTC, KCarretto commented on tavern/cli/tomeuploader/main.go
> +	client := &http.Client{}
Prefer using http.DefaultClient

2024-02-16 15:38 UTC, KCarretto commented on tavern/cli/tomeuploader/tomes/cat33/main.eldritch
Idk I kindve like them...

2025-01-02 00:22 UTC, closed without merging