Reverse shells
spellshift/realm pull request #699
Opened 2024-03-13 04:13 UTC by KCarretto

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

2024-03-15 05:11 UTC, KCarretto commented on tavern/internal/http/stream/mux.go
> +	if _, ok := m.Metadata["id"]; !ok {
Move this to a constant

2024-03-15 05:12 UTC, KCarretto commented on tavern/internal/http/stream/stream.go
> +// TODO: Docs
Add comments

2024-03-15 05:14 UTC, KCarretto commented on tavern/internal/http/stream/stream.go
> +		panic(fmt.Errorf("failed to generate random token: %w", err))
Don't panic just return ""

2024-03-15 05:15 UTC, KCarretto commented on tavern/internal/http/stream/stream.go
> +		// If no valid order key was provided, error but send the message
Delete outdated comments

2024-03-15 05:15 UTC, KCarretto commented on tavern/internal/http/stream/stream.go
> +		log.Printf("[ERROR] dropping message, subsequent message has already been sent")
Log message index (so it could be later correlated with gcpubsub)

2024-03-15 05:16 UTC, KCarretto commented on tavern/internal/http/stream/stream.go
> +			if len(buf.data) > 10 { // TODO: Magic Number
Move to constant

2024-03-15 05:20 UTC, KCarretto commented on tavern/internal/http/stream/websocket.go
> +					"id": c.id,
Move to constant

2024-03-15 05:20 UTC, KCarretto commented on tavern/internal/http/stream/websocket.go
> +			log.Printf("Shell not closed: %s", revShell.ClosedAt.String())
Remove debug logging

2024-03-15 05:21 UTC, KCarretto commented on tavern/internal/www/public/index.html
> +
Delete this

2024-03-15 05:24 UTC, KCarretto commented on implants/lib/eldritch/src/pivot/mod.rs
> +    fn reverse_shell_pty(this: &PivotLibrary, starlark_eval: &mut Evaluator<'v, '_>, cmd: Option<String>) -> anyhow::Result<NoneType> {
Figure out how to enable specifying optional env vars (e.g. no bash history)

2024-03-15 05:33 UTC, KCarretto commented on tavern/app.go
> +		// "/shell/ws":   stream.NewShellHandler(client, wsShellMux),
Delete comment

2024-03-15 05:36 UTC, KCarretto commented on tavern/internal/c2/api_reverse_shell.go
> +	defer func() {
Just defer, no need for the anonymous function

2024-03-15 05:37 UTC, KCarretto commented on tavern/internal/c2/api_reverse_shell.go
> +		// Notify Subscribers that the stream is closed
Move this comment down, and make this day prepare new context

2024-03-15 15:41 UTC, Cictrone commented on implants/lib/transport/src/grpc.rs
> +        rx: tokio::sync::mpsc::Receiver<ReverseShellRequest>,
maybe rename these

2024-03-15 16:47 UTC, Cictrone requested changes

2024-03-15 16:47 UTC, Cictrone commented on tavern/app.go
> +		"/graphql": tavernhttp.Endpoint{Handler: newGraphQLHandler(client, git)},
Why only some with new pattern?

2024-03-15 16:47 UTC, Cictrone commented on tavern/internal/http/stream/stream.go
> +	msg.Metadata["id"] = s.id
Use constant

2024-03-15 16:47 UTC, Cictrone commented on tavern/internal/http/stream/stream.go
> +		// log.Printf("[ERROR] received message without order key")
Maybe log?

2024-03-15 16:47 UTC, Cictrone commented on tavern/internal/http/stream/websocket.go
> +		shellIDStr := r.URL.Query().Get("shell_id")
const? 🤔

2024-03-15 16:47 UTC, Cictrone commented on tavern/internal/www/src/pages/shell/Shell.tsx
> +import '@xterm/xterm/css/xterm.css'
pls add a `;`

2024-03-15 16:47 UTC, Cictrone commented on tavern/tomes/reverse_shell/metadata.yml
> +tactic: EXECUTION
add set shell param

2024-03-15 21:47 UTC, KCarretto commented on tavern/app.go
> +		"/graphql": tavernhttp.Endpoint{Handler: newGraphQLHandler(client, git)},
Because we use Zero Values in golang :)

2024-03-15 22:07 UTC, KCarretto commented on implants/lib/eldritch/src/pivot/mod.rs
> +    fn reverse_shell_pty(this: &PivotLibrary, starlark_eval: &mut Evaluator<'v, '_>, cmd: Option<String>) -> anyhow::Result<NoneType> {
Maybe in a future PR, see http lib for example of passing map from eldritch

2024-03-16 01:03 UTC, Cictrone commented on implants/lib/eldritch/src/runtime/messages/reverse_shell_pty.rs
> +        // Appologies for the exclusionary language in the portable_pty dependency :(
nit: typo

2024-03-16 01:13 UTC, Cictrone submitted a review, later dismissed

2024-03-16 01:32 UTC, Cictrone approved these changes

2024-03-16 01:43 UTC, merged