Random.int added
spellshift/realm pull request #773
Opened 2024-05-12 00:12 UTC by chase1k

#### What type of PR is this?

/kind documentation
/kind feature
/kind eldritch-function

#### What this PR does / why we need it:

Adds random.int function to generate a secure random int

#### Which issue(s) this PR fixes:

Fixes #759

2024-05-12 14:06 UTC, hulto reviewed
Test

2024-05-12 14:06 UTC, hulto submitted a review, later dismissed
LGTM once tests pass

2024-05-12 14:06 UTC, hulto commented on implants/lib/eldritch/src/random/int_impl.rs
> +        let lower_bound = 0.90 * NUM_ITERATION as f64 / MAX_VALUE as f64;
I don't know math but seems okay.

2024-05-12 19:30 UTC, Cictrone requested changes
lgtm besides typo!

2024-05-12 19:30 UTC, Cictrone commented on docs/_docs/user-guide/eldritch.md
> +### radnom.int
nit: spelling

2024-07-05 21:21 UTC, chase1k commented on docs/_docs/user-guide/eldritch.md
> +### radnom.int
Fixed

2024-11-05 00:27 UTC, jabbate19 submitted a review, later dismissed

2024-12-29 03:17 UTC, hulto submitted a review, later dismissed
LGTM

2024-12-30 20:24 UTC, Cictrone approved these changes

2024-12-30 20:46 UTC, merged