Make host uniqueness modular
spellshift/realm pull request #785
Opened 2024-07-03 00:21 UTC by hulto

#### What type of PR is this?
Add one of the following kinds:
/kind feature

#### What this PR does / why we need it:
This PR provides greater control to admins when deploying the imix agent around how the uniqueness of a host is determined. In most red teaming situations writing a file to disk is unideal and the tradeoffs to use something else like mac address are worth it. This PR adds an environment variable override to the host ID and makes it easier for admins to implement and add their own uniqueness.

2024-07-04 19:25 UTC, Cictrone requested changes

2024-07-04 19:25 UTC, Cictrone commented on docs/_docs/user-guide/imix.md
> +| IMIX_HOST_ID | Manually specify the host ID for this beacon. Superceeds the file on disk. | - | No |
supersedes

2024-07-04 19:25 UTC, Cictrone commented on docs/_docs/dev-guide/imix.md
> +impl HostUniqueEngine for MacAddress {
HostIDSelector

2024-07-04 19:25 UTC, Cictrone commented on implants/imix/src/config.rs
> +        let engines = host_unique::defaults();
i think its default not defaults

2024-07-04 19:25 UTC, Cictrone commented on implants/imix/src/config.rs
> +            identifier: host_unique::id(engines).to_string(),
get_id_with_selectors

2024-07-04 19:25 UTC, Cictrone commented on implants/lib/host_unique/src/env.rs
> +        "env".to_string()
Maybe add more context?

2024-07-04 19:50 UTC, hulto commented on implants/imix/src/config.rs
> +        let engines = host_unique::defaults();
Can't have default on a trait.

2024-07-08 20:46 UTC, Cictrone approved these changes

2024-07-08 20:46 UTC, merged